name: Build and commit artifacts

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-room-card
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # Erst TS-Prüfung mit verständlichen Meldungen
      - name: Type-check (no emit)
        run: npx tsc --noEmit || true

      # Danach der eigentliche Build (ohne prebuild/yarn)
      - name: Build with webpack (verbose)
        run: npx webpack -c webpack.config.js --stats=errors-warnings --color

      - name: Verify outputs
        run: ls -l room-card.js room-card.js.gz

      - name: Commit built files (room-card.js + .gz)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build(ci): update room-card.js (+gz)"
          file_pattern: |
            room-card.js
            room-card.js.gz
