name: Push checks (no release)

on:
  push:
    branches: [ master ]
    # Triggert nur bei Quell-/Build-relevanten Dateien
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'webpack.config.js'
      - 'hacs.json'
      - '!**/.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'webpack.config.js'
      - 'hacs.json'
      - '!**/.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: push-checks-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # Nur Info, bricht nicht ab (hilfreich in Logs)
      - name: Type-check (no emit)
        run: npx tsc --noEmit || true

      # Baut einmal „trocken“, damit HACS nicht über fehlende Artefakte stolpert
      - name: Build (no artifacts committed here)
        run: npx webpack -c webpack.config.js --stats=errors-warnings --color

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: plugin
